name: First Workflow
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: myhelloworldaction
        run: echo "Hello World"
      - name: mynodeversionaction
        run: node -v
  run-powershell-commands:
    runs-on: windows-latest
    needs: [run-shell-commands]
    steps:
      - name: echo a string
        run: Write-Output "Hello Wide New World!"
  run-with-error:
    runs-on: ubuntu-latest
    steps:
      - name: multiline commands
        run: |
          node -v
          npm -v
          python -V
